---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBwY3+HsqkHzD/O2/WG89XCqS8PcOBH3QJ0Bn8BMTH47v1IKQ8W4/wwe8GG7qAeKpExdFHPTgJ+dK91joU1FtEg6lYvt2GCCSxP51qkTLqIBsm2cfUJOGqbPW4fU/Htv5CKYFcSLZomFTOUKia2D2hvMu4gQCIA/rsxBFkBUys/62lZx9doK5Vd1kCjtdeRQCiUeElo9KTMIIlE0/HXkYxAail/l6E+8mr+32nOdXZVbE27tTxXfSGU42PoS+TUR0uzR1I4kIIfYyPaS5htJEHPsA5Yrm+/oHev6rEwvUflEL+mxrbCxKv/20/UqHfcrZTOcRu2fWLLdxl/E6zl1CfyyYDqMejgHWFjtFq45353Fj14kIZjlHXgLrAuYggFntg8zuja4kNemFyHDqx8iMTNd0sqt2DURKfQkRC095S5wGSBzJrUxeckdlEb84S4oFqWFl+lBzSIy+Ym5nSKJ/ZdwMV3fs5YQdrqT2RVi2ElHqvf/PMBYIg8Be0dSv/veYyHaixOD5ku91+jfO/W5AI5TuBbmDmkPJh8orqPa7wUoP8x42WAIFwsc61GHrXd8cRI9SLOIVmdhYXR5iw0DvHjW9jeyvkEpjCNUSt7Vh6ATexCTNX7KpuMeNUXx4reYnEWPUCuQEI31/szcdholioR+5cuvdMXdrmLbVx50JxGb26Zk8T4CNdd9GDtsMHZ6/NG1x3DNM4VKJeE+NImx6CTWPiRqIzMiwA=
    admin-user: AgAp6v1fBb6Tp9MHFURnkP6UjaQ+i783WJQMszmfm1bQH7DePZgcYzuPpDx+2OWUSHfN0sfpGWYEdNIPKABCRM7BjJrWRYV+W7EtnIu9TnTwbFxLJUp13AEukHhaWKXu8gsxGarWraPAWSTBJG3kt/T1RZX9NVKAfofM9UR76/D+2o0SAlX/rwxp2G3KhJfUWPdYjA0e4bZTXKc5wM1UbnTyZASYk5yU3hsaSPvKjz1qKIGS3VMv8tBb6W3GjFGajIaBb/FovAQSJtyhxuYKqlg5VO5CweKDZFcoYI4Rnrp4UQK6IzwMVn3lkEOrT3DbOPfzBxFMFncLOnV+LgXM8gOPhwg5rp51Kv6NQARBiBV83RV3+lNOt7kZzP/1kK85qzjQxpj08rRCj8OiO3v6NoQlYUPigBja5ylf65GrnCKr8JhV+aLPpZ5LonR41JGkE41F+i45R+tpp3OECMLHOE1t49FsW7+USr2haTEQ37QkpGnudKUTF1PV6uxdKxPttz/EGHprYrFlelUl6fEGpBg7vsBpQfRk02jTUxOKc6S79TvdfA7Wqf23ihblpVL0qf+fkwZqLSJ6hJnDWWnL6BCoEDHXALsiNhib5d4mo20buSb8z6OyQsFZG7W6n+DMA/RDRiRTRdgcoEgvbMmTc+Mup6FOzXPg6JmRVRuRFJhHtgyBPrl8C3WaGJ5HlxHo2Fy9egl5aw==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
