apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: local
servers: 1
agents: 1
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6444"
ports:
  - port: 127.0.0.1:80:80
    nodeFilters:
      - loadbalancer
  - port: 127.0.0.1:443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    disableLoadbalancer: false
